export const medicationOptions = [
    { label: "Pain Killers", value: "pain_killers" },
    { label: "Antibiotics", value: "antibiotics" },
    { label: "Cold & Flu", value: "cold_and_flu" },
    { label: "Cough & Congestion", value: "cough_congestion" },
    { label: "Emergency Contraception", value: "emergency_contraception" },
    { label: "Antidepressants", value: "antidepressants" },
    { label: "Anti-inflammatory Drugs", value: "anti_inflammatory" },
    { label: "Blood Pressure", value: "blood_pressure" },
    { label: "Diabetes", value: "diabetes_medication" },
    { label: "Mood Stabilizers", value: "mood_stabilizers" },
    { label: "Cholesterol", value: "cholesterol_medication" },
    { label: "Asthma Inhalers", value: "asthma_inhalers" },
    { label: "Sleep Aids", value: "sleep_aids" },
    { label: "Anti-Anxiety", value: "anti_anxiety" },
    { label: "Allergy", value: "allergy" },
    { label: "Other", value: "other" },
];
