export const symptomOptions = [
  { label: "Pain Free", value: "pain_free" },
  { label: "Cramps", value: "cramps" },
  { label: "Headache", value: "headache" },
  { label: "Migraine", value: "migraine" },
  { label: "Nausea", value: "nausea" },
  { label: "Fatigue", value: "fatigue" },
  { label: "Back Pain", value: "back_pain" },
  { label: "Bloating", value: "bloating" },
  { label: "Sleep Issues", value: "sleep_issues" },
  { label: "Muscle Aches", value: "muscle_aches" },
  { label: "Joint Pain", value: "joint_pain" },
  { label: "Acne", value: "acne" },
  { label: "Mood Swings", value: "mood_swings" },
  { label: "Diarrhea", value: "diarrhea" },
  { label: "Constipation", value: "constipation" },
  { label: "Increased Appetite", value: "increased_appetite" },
  { label: "Decreased Appetite", value: "decreased_appetite" },
  { label: "Breast Tenderness", value: "breat_tenderness" },
];
