import { useEffect, useCallback } from "react";
import { StyleSheet, View } from "react-native";
import {
  insertDay,
  insertSymptom,
  insertMood,
  getDay,
  getSymptom,
  getMood,
  getSymptomEntriesForDay,
  getMoodEntriesForDay,
  getSymptomByID,
  getMoodByID,
  deleteSymptomEntry,
  deleteMoodEntry,
  insertSymptomEntry,
  insertMoodEntry,
} from "@/db/database";
import {
  List,
  Button,
  Text,
  useTheme,
  RadioButton,
  Divider,
  TextInput,
  Chip,
} from "react-native-paper";
import { symptomOptions } from "@/constants/Symptoms";
import { moodOptions } from "@/constants/Moods";
import {
  useAccordion,
  useMoods,
  useSelectedDate,
  useSymptoms,
} from "@/assets/src/calendar-storage";

const flowOptions = ["None", "Spotting", "Light", "Medium", "Heavy"];

// radio buttons adapted from code generated by ChatGPT-4o
function FlowRadioButtons({
  selectedOption,
  setSelectedOption,
}: {
  selectedOption: number;
  setSelectedOption: (option: number) => void;
}) {
  const theme = useTheme();

  return (
    <View style={{ width: "100%" }}>
      <RadioButton.Group
        value={flowOptions[selectedOption]}
        onValueChange={(value) => setSelectedOption(flowOptions.indexOf(value))}
      >
        {flowOptions.map((button, index) => (
          <RadioButton.Item
            key={button}
            label={button}
            value={button}
            labelStyle={{
              color:
                selectedOption === index
                  ? theme.colors.onSecondaryContainer
                  : theme.colors.onSurfaceVariant,
            }}
          ></RadioButton.Item>
        ))}
      </RadioButton.Group>
    </View>
  );
}

function ChipSelection({
  options,
  selectedValues,
  setSelectedValues,
  label,
}: {
  options: { label: string; value: string }[];
  selectedValues: string[];
  setSelectedValues: (values: string[]) => void;
  label: string;
}) {
  const theme = useTheme();

  return (
    <View style={{ padding: 16 }}>
      <Text style={styles.sectionLabel}>{label}</Text>
      <View style={styles.chipContainer}>
        {options.map((option) => (
          <Chip
            mode="outlined"
            key={option.value}
            selected={selectedValues.includes(option.value)}
            showSelectedCheck={false}
            onPress={() => {
              setSelectedValues(
                selectedValues.includes(option.value)
                  ? selectedValues.filter((val) => val !== option.value)
                  : [...selectedValues, option.value],
              );
            }}
            style={{
              backgroundColor: selectedValues.includes(option.value)
                ? theme.colors.onSecondary
                : theme.colors.secondary,
              margin: 4,
            }}
            textStyle={{
              color: selectedValues.includes(option.value)
                ? theme.colors.onSecondaryContainer
                : theme.colors.secondaryContainer,
            }}
          >
            {option.label}
          </Chip>
        ))}
      </View>
    </View>
  );
}

export default function DayView() {
  const theme = useTheme();
  const { state, setExpandedAccordion } = useAccordion();

  const { selectedMoods, setSelectedMoods } = useMoods();
  const { date, flow_intensity, notes, setFlow, setNotes } = useSelectedDate();
  const { selectedSymptoms, setSelectedSymptoms } = useSymptoms();

  const syncEntries = async (
    selectedValues: string[],
    type: "symptom" | "mood",
  ) => {
    const day = await getDay(date);
    if (!day) return;

    const existingEntries =
      type === "symptom"
        ? await getSymptomEntriesForDay(day.id)
        : await getMoodEntriesForDay(day.id);

    const insertEntry =
      type === "symptom" ? insertSymptomEntry : insertMoodEntry;
    const deleteEntry =
      type === "symptom" ? deleteSymptomEntry : deleteMoodEntry;
    const getItem = type === "symptom" ? getSymptom : getMood;
    const insertItem = type === "symptom" ? insertSymptom : insertMood;

    for (const value of selectedValues) {
      let item = await getItem(value);
      if (!item) {
        await insertItem(value, true);
        item = await getItem(value);
      }
      if (item) {
        await insertEntry(day.id, item.id);
      }
    }

    const selectedIds = await Promise.all(
      selectedValues.map(async (value) => {
        const item =
          type === "symptom" ? await getSymptom(value) : await getMood(value);
        return item?.id ?? null;
      }),
    );

    const validIds = selectedIds.filter((id) => id !== null);
    for (const entry of existingEntries) {
      const entryId =
        type === "symptom"
          ? (entry as { symptom_id: number }).symptom_id
          : (entry as { mood_id: number }).mood_id;
      if (
        (type === "symptom" && !validIds.includes(entryId)) ||
        (type === "mood" && !validIds.includes(entryId))
      ) {
        await deleteEntry(entry.id);
      }
    }
  };

  const fetchEntries = useCallback(
    async (type: "symptom" | "mood") => {
      const getEntries =
        type === "symptom" ? getSymptomEntriesForDay : getMoodEntriesForDay;
      const getById = type === "symptom" ? getSymptomByID : getMoodByID;
      const setSelected =
        type === "symptom" ? setSelectedSymptoms : setSelectedMoods;

      const day = await getDay(date);
      if (!day) {
        setSelected([]);
        return;
      }

      const entries = await getEntries(day.id);
      const values = await Promise.all(
        entries.map(async (entry) => {
          const id =
            type === "symptom"
              ? (entry as { symptom_id: number }).symptom_id
              : (entry as { mood_id: number }).mood_id;
          const item = await getById(id);
          return item?.name ?? null;
        }),
      );
      setSelected(values.filter((value) => value !== null) as string[]);
    },
    [date], // eslint-disable-line react-hooks/exhaustive-deps
  );

  const fetchNotes = useCallback(async () => {
    const day = await getDay(date);
    if (day && day.notes) {
      setNotes(day.notes);
    } else {
      setNotes("");
    }
  }, [date]); // eslint-disable-line react-hooks/exhaustive-deps

  function onSave() {
    insertDay(date, flow_intensity, notes).then(async () => {
      setFlow(flow_intensity);
      setExpandedAccordion(null);

      await syncEntries(selectedSymptoms, "symptom");
      await syncEntries(selectedMoods, "mood");
      await fetchEntries("symptom");
      await fetchEntries("mood");
      await fetchNotes();
    });
  }

  useEffect(() => {
    setFlow(flow_intensity);
    fetchEntries("symptom");
    fetchEntries("mood");
    fetchNotes();
    setExpandedAccordion(null);
  }, [setFlow, fetchEntries, fetchNotes]); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <View style={{ backgroundColor: theme.colors.background }}>
      <View style={styles.titleContainer}>
        <Text variant="titleLarge">
          {new Intl.DateTimeFormat("en-US", {
            weekday: "short",
            month: "short",
            day: "numeric",
            year: "numeric",
          }).format(new Date(date + "T00:00:00"))}
        </Text>
        <Button mode="elevated" onPress={() => onSave()}>
          Save
        </Button>
      </View>
      <View>
        <List.Section>
          <List.Accordion
            title={"Flow Intensity   |   " + flowOptions[flow_intensity]}
            expanded={state === "flow"}
            onPress={() =>
              setExpandedAccordion(state === "flow" ? null : "flow")
            }
            left={(props) => <List.Icon {...props} icon="water" />}
          >
            <FlowRadioButtons
              selectedOption={flow_intensity}
              setSelectedOption={setFlow}
            />
          </List.Accordion>
          <Divider />

          <List.Accordion
            title={"Symptoms   |   " + selectedSymptoms.length + " Selected"}
            expanded={state === "symptoms"}
            onPress={() =>
              setExpandedAccordion(state === "symptoms" ? null : "symptoms")
            }
            left={(props) => <List.Icon {...props} icon="alert-decagram" />}
          >
            <ChipSelection
              options={symptomOptions}
              selectedValues={selectedSymptoms}
              setSelectedValues={setSelectedSymptoms}
              label="Select Symptoms:"
            />
          </List.Accordion>
          <Divider />
          <List.Accordion
            title={"Moods   |   " + selectedMoods.length + " Selected"}
            expanded={state === "mood"}
            onPress={() =>
              setExpandedAccordion(state === "mood" ? null : "mood")
            }
            left={(props) => <List.Icon {...props} icon="emoticon" />}
          >
            <ChipSelection
              options={moodOptions}
              selectedValues={selectedMoods}
              setSelectedValues={setSelectedMoods}
              label="Select Moods:"
            />
          </List.Accordion>
          <Divider />
          <List.Accordion
            title="Medications"
            expanded={state === "medications"}
            onPress={() =>
              setExpandedAccordion(
                state === "medications" ? null : "medications",
              )
            }
            left={(props) => <List.Icon {...props} icon="pill" />}
          >
            <View style={{ padding: 16 }}>
              <Text>Nothing here yet!</Text>
            </View>
          </List.Accordion>
          <Divider />
          <List.Accordion
            title="Notes"
            expanded={state === "notes"}
            onPress={() =>
              setExpandedAccordion(state === "notes" ? null : "notes")
            }
            left={(props) => <List.Icon {...props} icon="note" />}
          >
            <View style={{ padding: 16 }}>
              <TextInput
                label="Notes"
                value={notes}
                onChangeText={(notes) => setNotes(notes)}
                placeholder="Add Notes..."
              />
            </View>
          </List.Accordion>
        </List.Section>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  titleContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
  },
  chipContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  sectionLabel: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 8,
  },
});
